insert into division (name) values ('Ayeyarwady Region');
insert into division (name) values ('Bago Region');
insert into division (name) values ('Chin State');
insert into division (name) values ('Kachin State');
insert into division (name) values ('Kayah State');
insert into division (name) values ('Kayin State');
insert into division (name) values ('Magway Region');
insert into division (name) values ('Mandalay Region');
insert into division (name) values ('Mon State');
insert into division (name) values ('Rakhine State');
insert into division (name) values ('Shan State');
insert into division (name) values ('Sagaing Region');
insert into division (name) values ('Tanintharyi Region');
insert into division (name) values ('Yangon Region');
insert into division (name) values ('Naypyidaw Union Territory');

-- Ayeyawady
insert into township (division_id, name) values (1, 'Hinthada township');
insert into township (division_id, name) values (1, 'Lemyethna township');
insert into township (division_id, name) values (1, 'Zalun township');
insert into township (division_id, name) values (1, 'Ithapyu township');
insert into township (division_id, name) values (1, 'Labutta township');
insert into township (division_id, name) values (1, 'Mawlamyinegyun township');
insert into township (division_id, name) values (1, 'Kyonmanage township');
insert into township (division_id, name) values (1, 'Pyinsalu township');
insert into township (division_id, name) values (1, 'Danubyu township');
insert into township (division_id, name) values (1, 'Ma-ubin township');
insert into township (division_id, name) values (1, 'Nyaungdon township');
insert into township (division_id, name) values (1, 'Pantanaw township');
insert into township (division_id, name) values (1, 'Einme township');
insert into township (division_id, name) values (1, 'Myaungmya township');
insert into township (division_id, name) values (1, 'Wakema township');
insert into township (division_id, name) values (1, 'Shwelaung township');
insert into township (division_id, name) values (1, 'Kangyidaunk township');
insert into township (division_id, name) values (1, 'Ngapudaw township');
insert into township (division_id, name) values (1, 'Pathein township');
insert into township (division_id, name) values (1, 'Thabaung township');
insert into township (division_id, name) values (1, 'Chaungtha township');
insert into township (division_id, name) values (1, 'Hainggyi township');
insert into township (division_id, name) values (1, 'Ngayokekaung township');
insert into township (division_id, name) values (1, 'Ngwesaung township');
insert into township (division_id, name) values (1, 'Bogale township');
insert into township (division_id, name) values (1, 'Dedaye township');
insert into township (division_id, name) values (1, 'Kyaiklat township');
insert into township (division_id, name) values (1, 'Pyapon township');
insert into township (division_id, name) values (1, 'Ahmar township');
insert into township (division_id, name) values (1, 'Kyaunggon township');
insert into township (division_id, name) values (1, 'Kyonpyaw township');
insert into township (division_id, name) values (1, 'Yekyi township');
insert into township (division_id, name) values (1, 'Ahtaung township');
insert into township (division_id, name) values (1, 'Ngathinechaung township');
insert into township (division_id, name) values (1, 'Ingapu township');
insert into township (division_id, name) values (1, 'Kyangin township');
insert into township (division_id, name) values (1, 'Myanaung township');
insert into township (division_id, name) values (1, 'Kanaung township');


-- Bago
insert into township (division_id, name) values (2, 'Bago township');
insert into township (division_id, name) values (2, 'Daik-U township');
insert into township (division_id, name) values (2, 'Kawa township');
insert into township (division_id, name) values (2, 'Nyaunglebin township');
insert into township (division_id, name) values (2, 'Shwegyin township');
insert into township (division_id, name) values (2, 'Thanatpin township');
insert into township (division_id, name) values (2, 'Waw township');
insert into township (division_id, name) values (2, 'Kyauktaga township');
insert into township (division_id, name) values (2, 'Kyaukkyi township');
insert into township (division_id, name) values (2, 'Oktwin township');
insert into township (division_id, name) values (2, 'Pyu township');
insert into township (division_id, name) values (2, 'Tantabin township');
insert into township (division_id, name) values (2, 'Taungoo township');
insert into township (division_id, name) values (2, 'Yedashe township');
insert into township (division_id, name) values (2, 'Pandaung township');
insert into township (division_id, name) values (2, 'Paukkaung township');
insert into township (division_id, name) values (2, 'Paungde township');
insert into township (division_id, name) values (2, 'Pyay township');
insert into township (division_id, name) values (2, 'Shwedaung township');
insert into township (division_id, name) values (2, 'Thegon township');
insert into township (division_id, name) values (2, 'Gyobingauk township');
insert into township (division_id, name) values (2, 'Letpadan township');
insert into township (division_id, name) values (2, 'Minhla township');
insert into township (division_id, name) values (2, 'Monyo township');
insert into township (division_id, name) values (2, 'Okpho township');
insert into township (division_id, name) values (2, 'Tharrawaddy township');
insert into township (division_id, name) values (2, 'Nattalin township');
insert into township (division_id, name) values (2, 'Zigon township');

-- Chin
insert into township (division_id, name) values (3, 'Falam township');
insert into township (division_id, name) values (3, 'Tiddim township');
insert into township (division_id, name) values (3, 'Ton Zang township');
insert into township (division_id, name) values (3, 'Hakha township');
insert into township (division_id, name) values (3, 'Htantlang township');
insert into township (division_id, name) values (3, 'Matupi township');
insert into township (division_id, name) values (3, 'Paletwa township');
insert into township (division_id, name) values (3, 'Kanpetlet township');
insert into township (division_id, name) values (3, 'Mindat township');

-- Kachin
insert into township (division_id, name) values (4, 'Bhamo township');
insert into township (division_id, name) values (4, 'Mansi township');
insert into township (division_id, name) values (4, 'Momauk township');
insert into township (division_id, name) values (4, 'Shwegu township');
insert into township (division_id, name) values (4, 'Mogaung township');
insert into township (division_id, name) values (4, 'Mohnyin township');
insert into township (division_id, name) values (4, 'Phakant township');
insert into township (division_id, name) values (4, 'Chipwi township');
insert into township (division_id, name) values (4, 'Hsawlaw township');
insert into township (division_id, name) values (4, 'Injangyang township');
insert into township (division_id, name) values (4, 'Myitkyina township');
insert into township (division_id, name) values (4, 'Tanai township');
insert into township (division_id, name) values (4, 'Waingmaw township');
insert into township (division_id, name) values (4, 'Kawnglanghpu township');
insert into township (division_id, name) values (4, 'Machanbaw township');
insert into township (division_id, name) values (4, 'Nogmung township');
insert into township (division_id, name) values (4, 'Putao township');
insert into township (division_id, name) values (4, 'Sumprabum township');

-- Kayah
insert into township (division_id, name) values (5, 'Bawlakhe township');
insert into township (division_id, name) values (5, 'Hpasawng township');
insert into township (division_id, name) values (5, 'Mese township');
insert into township (division_id, name) values (5, 'Ywathit Subtownship');
insert into township (division_id, name) values (5, 'Demoso township');
insert into township (division_id, name) values (5, 'Hpruso township');
insert into township (division_id, name) values (5, 'Loikaw township');
insert into township (division_id, name) values (5, 'Shadaw township');

-- Kayin
insert into township (division_id, name) values (6, 'Hlaingbwe township');
insert into township (division_id, name) values (6, 'Hpa-an township');
insert into township (division_id, name) values (6, 'Thandaunggyi township');
insert into township (division_id, name) values (6, 'Hpapun township');
insert into township (division_id, name) values (6, 'Kawkareik township');
insert into township (division_id, name) values (6, 'Kyain Seikgyi township');
insert into township (division_id, name) values (6, 'Myawaddy township');

-- Magway
insert into township (division_id, name) values (7, 'Gangaw township');
insert into township (division_id, name) values (7, 'Saw township');
insert into township (division_id, name) values (7, 'Htilin township');
insert into township (division_id, name) values (7, 'Kyaukhtu Subtownship');
insert into township (division_id, name) values (7, 'Chauk township');
insert into township (division_id, name) values (7, 'Magway township');
insert into township (division_id, name) values (7, 'Myothit township');
insert into township (division_id, name) values (7, 'Natmauk township');
insert into township (division_id, name) values (7, 'Taungdwingyi township');
insert into township (division_id, name) values (7, 'Yenangyaung township');
insert into township (division_id, name) values (7, 'Minbu township');
insert into township (division_id, name) values (7, 'Ngape township');
insert into township (division_id, name) values (7, 'Pwintbyu township');
insert into township (division_id, name) values (7, 'Salin township');
insert into township (division_id, name) values (7, 'Sidoktaya township');
insert into township (division_id, name) values (7, 'Myaing township');
insert into township (division_id, name) values (7, 'Pakokku township');
insert into township (division_id, name) values (7, 'Pauk township');
insert into township (division_id, name) values (7, 'Seikphyu township');
insert into township (division_id, name) values (7, 'Yesagyo township');
insert into township (division_id, name) values (7, 'Aunglan township');
insert into township (division_id, name) values (7, 'Kamma township');
insert into township (division_id, name) values (7, 'Mindon township');
insert into township (division_id, name) values (7, 'Minhla township');
insert into township (division_id, name) values (7, 'Sinbaungwe township');
insert into township (division_id, name) values (7, 'Thayet township');

-- Mandalay
insert into township (division_id, name) values (8, 'Kyaukse township');
insert into township (division_id, name) values (8, 'Myittha township');
insert into township (division_id, name) values (8, 'Sintgaing township');
insert into township (division_id, name) values (8, 'Tada-U township');
insert into township (division_id, name) values (8, 'Amarapura township');
insert into township (division_id, name) values (8, 'Aungmyethazan township');
insert into township (division_id, name) values (8, 'Chanayethazan township');
insert into township (division_id, name) values (8, 'Chanmyathazi township');
insert into township (division_id, name) values (8, 'Maha Aungmye township');
insert into township (division_id, name) values (8, 'Patheingyi township');
insert into township (division_id, name) values (8, 'Pyigyidagun township');
insert into township (division_id, name) values (8, 'Mahlaing township');
insert into township (division_id, name) values (8, 'Meiktila township');
insert into township (division_id, name) values (8, 'Thazi township');
insert into township (division_id, name) values (8, 'Wundwin township');
insert into township (division_id, name) values (8, 'Myingyan township');
insert into township (division_id, name) values (8, 'Natogyi township');
insert into township (division_id, name) values (8, 'Ngazun township');
insert into township (division_id, name) values (8, 'Taungtha township');
insert into township (division_id, name) values (8, 'Kyaukpadaung township');
insert into township (division_id, name) values (8, 'Nyaung-U township');
insert into township (division_id, name) values (8, 'Ngathayauk Subtownship');
insert into township (division_id, name) values (8, 'Madaya township');
insert into township (division_id, name) values (8, 'Mogok township');
insert into township (division_id, name) values (8, 'Pyinoolwin township');
insert into township (division_id, name) values (8, 'Singu township');
insert into township (division_id, name) values (8, 'Thabeikkyin township');
insert into township (division_id, name) values (8, 'Pyawbwe township');
insert into township (division_id, name) values (8, 'Yamethin Townshi');

-- Mon
insert into township (division_id, name) values (9, 'Chaungzon township');
insert into township (division_id, name) values (9, 'Kyaikmaraw township');
insert into township (division_id, name) values (9, 'Mawlamyine township');
insert into township (division_id, name) values (9, 'Mudon township');
insert into township (division_id, name) values (9, 'Thanbyuzayat township');
insert into township (division_id, name) values (9, 'Ye township');
insert into township (division_id, name) values (9, 'Bilin township');
insert into township (division_id, name) values (9, 'Kyaikto township');
insert into township (division_id, name) values (9, 'Paung township');
insert into township (division_id, name) values (9, 'Thaton township');

-- Rakhine
insert into township (division_id, name) values (10, 'Ann township');
insert into township (division_id, name) values (10, 'Kyaukpyu township');
insert into township (division_id, name) values (10, 'Manaung township');
insert into township (division_id, name) values (10, 'Ramree township');
insert into township (division_id, name) values (10, 'Buthidaung township');
insert into township (division_id, name) values (10, 'Maungdaw township');
insert into township (division_id, name) values (10, 'Pauktaw township');
insert into township (division_id, name) values (10, 'Ponnagyun township');
insert into township (division_id, name) values (10, 'Rathedaung township');
insert into township (division_id, name) values (10, 'Sittwe township');
insert into township (division_id, name) values (10, 'Thandwe township');
insert into township (division_id, name) values (10, 'Toungup township');
insert into township (division_id, name) values (10, 'Gwa township');
insert into township (division_id, name) values (10, 'Maei Subtownship');
insert into township (division_id, name) values (10, 'Kyeintali Subtownship');
insert into township (division_id, name) values (10, 'Kyauktaw township');
insert into township (division_id, name) values (10, 'Minbya township');
insert into township (division_id, name) values (10, 'Mrauk-U township');
insert into township (division_id, name) values (10, 'Myebon township');

-- Shan
insert into township (division_id, name) values (11, 'Kengtung township');
insert into township (division_id, name) values (11, 'Mong Khet township');
insert into township (division_id, name) values (11, 'Mong La township (SR4)');
insert into township (division_id, name) values (11, 'Mong Yang township');
insert into township (division_id, name) values (11, 'Mine Pauk Subtownship');
insert into township (division_id, name) values (11, 'Minelar Subtownship');
insert into township (division_id, name) values (11, 'Mong Hpayak township (SR4)');
insert into township (division_id, name) values (11, 'Mong Yawng township');
insert into township (division_id, name) values (11, 'Mineyu Subtownship');
insert into township (division_id, name) values (11, 'Mong Hsat township');
insert into township (division_id, name) values (11, 'Mong Ping township');
insert into township (division_id, name) values (11, 'Mong Tong township');
insert into township (division_id, name) values (11, 'Minekoke Subtownship');
insert into township (division_id, name) values (11, 'Monehta Subtownship');
insert into township (division_id, name) values (11, 'Ponparkyin Subtownship');
insert into township (division_id, name) values (11, 'Tontar Subtownship');;
insert into township (division_id, name) values (11, 'Tachileik township')
insert into township (division_id, name) values (11, 'Kyaing Lap Subtownship (Kenglap)');
insert into township (division_id, name) values (11, 'Talay Subtownship');
insert into township (division_id, name) values (11, 'Kunlong township');
insert into township (division_id, name) values (11, 'Hsipaw township');
insert into township (division_id, name) values (11, 'Kyaukme township');
insert into township (division_id, name) values (11, 'Namtu township');
insert into township (division_id, name) values (11, 'Nawnghkio township');
insert into township (division_id, name) values (11, 'Minelon Subtownship');
insert into township (division_id, name) values (11, 'Minengaw Subtownship');
insert into township (division_id, name) values (11, 'Hseni township');
insert into township (division_id, name) values (11, 'Lashio township');
insert into township (division_id, name) values (11, 'Mongyai township');
insert into township (division_id, name) values (11, 'Tangyan township');
insert into township (division_id, name) values (11, 'see Kokang Self-Administered Zone');
insert into township (division_id, name) values (11, 'Kutkai township');
insert into township (division_id, name) values (11, 'Mu Se township');
insert into township (division_id, name) values (11, 'Nanhkan township');
insert into township (division_id, name) values (11, 'Manhero Subtownship');
insert into township (division_id, name) values (11, 'Monekoe Subtownship');
insert into township (division_id, name) values (11, 'Pansai Subtownship (Kyu-kok)');
insert into township (division_id, name) values (11, 'Tamoenye Subtownship');
insert into township (division_id, name) values (11, 'see Wa Self-Administered division');
insert into township (division_id, name) values (11, 'see Wa Self-Administered division');
insert into township (division_id, name) values (11, 'Mabein township');
insert into township (division_id, name) values (11, 'Mongmit township');
insert into township (division_id, name) values (11, 'Laukkaing township');
insert into township (division_id, name) values (11, 'Konkyan township');
insert into township (division_id, name) values (11, 'Chinshwehaw Subtownship');
insert into township (division_id, name) values (11, 'Mawhtike Subtownship');
insert into township (division_id, name) values (11, 'Mantong township1');
insert into township (division_id, name) values (11, 'Namhsan township1');
insert into township (division_id, name) values (11, 'Hopang township');
insert into township (division_id, name) values (11, 'Mongmaw township (Minemaw)');
insert into township (division_id, name) values (11, 'Pangwaun township (Panwine)');
insert into township (division_id, name) values (11, 'Namtit Subtownship');
insert into township (division_id, name) values (11, 'Panlong Subtownship');
insert into township (division_id, name) values (11, 'Matman township (Metman)');
insert into township (division_id, name) values (11, 'Namphan township (Naphang)');
insert into township (division_id, name) values (11, 'Pangsang township (Pan San)');
insert into township (division_id, name) values (11, 'Man Kan Subtownship');
insert into township (division_id, name) values (11, 'Langhko township');
insert into township (division_id, name) values (11, 'Mawkmai township');
insert into township (division_id, name) values (11, 'Mong Nai township');
insert into township (division_id, name) values (11, 'Mong Pan township');
insert into township (division_id, name) values (11, 'Homane Subtownship');
insert into township (division_id, name) values (11, 'Kengtaung Subtownship');
insert into township (division_id, name) values (11, 'Kunhing township');
insert into township (division_id, name) values (11, 'Kyethi township');
insert into township (division_id, name) values (11, 'Lai-Hka township');
insert into township (division_id, name) values (11, 'Loilen township');
insert into township (division_id, name) values (11, 'Mong Hsu township');
insert into township (division_id, name) values (11, 'Mong Kung township');
insert into township (division_id, name) values (11, 'Nansang township');
insert into township (division_id, name) values (11, 'Karli Subtownship');
insert into township (division_id, name) values (11, 'Kholan Subtownship');
insert into township (division_id, name) values (11, 'Minenaung Subtownship');
insert into township (division_id, name) values (11, 'Minesan Subtownship');
insert into township (division_id, name) values (11, 'Panglong Subtownship');
insert into township (division_id, name) values (11, 'Kalaw township');
insert into township (division_id, name) values (11, 'Lawksawk township');
insert into township (division_id, name) values (11, 'Nyaungshwe township');
insert into township (division_id, name) values (11, 'Pekon township');
insert into township (division_id, name) values (11, 'Taunggyi township');
insert into township (division_id, name) values (11, 'Indaw Subtownship');
insert into township (division_id, name) values (11, 'Kyauktalongyi Subtownship');
insert into township (division_id, name) values (11, 'Naungtayar Subtownship');
insert into township (division_id, name) values (11, 'Pindaya township');
insert into township (division_id, name) values (11, 'Ywangan township');
insert into township (division_id, name) values (11, 'Hopong township');
insert into township (division_id, name) values (11, 'Hsi Hseng township');
insert into township (division_id, name) values (11, 'Pinlaung township');

-- Sagaing
insert into township (division_id, name) values (12, 'Hkamti township (Singkaling Hkamti)');
insert into township (division_id, name) values (12, 'Homalin township (Homalin)');
insert into township (division_id, name) values (12, 'Kanbalu township (Kanbalu)');
insert into township (division_id, name) values (12, 'Kyunhla township (Kyunhla)');
insert into township (division_id, name) values (12, 'Taze township (Taze)');
insert into township (division_id, name) values (12, 'Ye-U township (Ye-U)');
insert into township (division_id, name) values (12, 'Kale township (Kalaymyo)');
insert into township (division_id, name) values (12, 'Kalewa township (Kalewa)');
insert into township (division_id, name) values (12, 'Mingin township (Mingin)');
insert into township (division_id, name) values (12, 'Banmauk township (Banmauk)');
insert into township (division_id, name) values (12, 'Indaw township (Indaw)');
insert into township (division_id, name) values (12, 'Katha township (Katha)');
insert into township (division_id, name) values (12, 'Kawlin township (Kawlin)');
insert into township (division_id, name) values (12, 'Pinlebu township (Pinlebu)');
insert into township (division_id, name) values (12, 'Htigyaing township (Htigyaing)');
insert into township (division_id, name) values (12, 'Wuntho township (Wuntho)');
insert into township (division_id, name) values (12, 'Mawlaik township (Mawlaik)');
insert into township (division_id, name) values (12, 'Paungbyin township (Paungbyin)');
insert into township (division_id, name) values (12, 'Ayadaw township (Ayadaw)');
insert into township (division_id, name) values (12, 'Budalin township (Budalin)');
insert into township (division_id, name) values (12, 'Chaung-U township (Chaung-U)');
insert into township (division_id, name) values (12, 'Monywa township (Monywa)');
insert into township (division_id, name) values (12, 'Myaung township (Myaung)');
insert into township (division_id, name) values (12, 'Myinmu township (Myinmu)');
insert into township (division_id, name) values (12, 'Sagaing township (Sagaing)');
insert into township (division_id, name) values (12, 'Khin-U township (Khin-U)');
insert into township (division_id, name) values (12, 'Shwebo township (Shwebo)');
insert into township (division_id, name) values (12, 'Wetlet township (Wetlet)');
insert into township (division_id, name) values (12, 'Tabayin township (Tabayin)');
insert into township (division_id, name) values (12, 'Tamu township (Tamu)');
insert into township (division_id, name) values (12, 'Kani township (Kani)');
insert into township (division_id, name) values (12, 'Pale township (Pale)');
insert into township (division_id, name) values (12, 'Salingyi township (Salingyi)');
insert into township (division_id, name) values (12, 'Yinmabin township (Yinmabin)');
insert into township (division_id, name) values (12, 'Lahe township (Lahe)');
insert into township (division_id, name) values (12, 'Leshi township (Leshi)');
insert into township (division_id, name) values (12, 'Nanyun township (Nanyun)');

-- Tanintharyi
insert into township (division_id, name) values (13, 'Dawei township');
insert into township (division_id, name) values (13, 'Launglon township');
insert into township (division_id, name) values (13, 'Thayetchaung township');
insert into township (division_id, name) values (13, 'Yebyu township');
insert into township (division_id, name) values (13, 'Kaleinaung Subtownship');
insert into township (division_id, name) values (13, 'Myitta Subtownship');
insert into township (division_id, name) values (13, 'Bokpyin township');
insert into township (division_id, name) values (13, 'Kawthaung township');
insert into township (division_id, name) values (13, 'Karathuri Subtownship');
insert into township (division_id, name) values (13, 'Khamaukgyi Subtownship');
insert into township (division_id, name) values (13, 'Pyigyimandaing Subtownship');
insert into township (division_id, name) values (13, 'Kyunsu township');
insert into township (division_id, name) values (13, 'Myeik township');
insert into township (division_id, name) values (13, 'Palaw township');
insert into township (division_id, name) values (13, 'Tanintharyi township');
insert into township (division_id, name) values (13, 'Palauk Subtownship');

-- Yangon
insert into township (division_id, name) values (14, 'Botataung township');
insert into township (division_id, name) values (14, 'Dagon Seikkan township');
insert into township (division_id, name) values (14, 'East Dagon township');
insert into township (division_id, name) values (14, 'North Dagon township');
insert into township (division_id, name) values (14, 'North Okkalapa township');
insert into township (division_id, name) values (14, 'Pazundaung township');
insert into township (division_id, name) values (14, 'South Dagon township');
insert into township (division_id, name) values (14, 'South Okkalapa township');
insert into township (division_id, name) values (14, 'Thingangyun township');
insert into township (division_id, name) values (14, 'Dawbon township1');
insert into township (division_id, name) values (14, 'Mingala Taungnyunt township1');
insert into township (division_id, name) values (14, 'Tamwe township1');
insert into township (division_id, name) values (14, 'Thaketa township1');
insert into township (division_id, name) values (14, 'Yankin township1');
insert into township (division_id, name) values (14, 'Hlaingthaya township');
insert into township (division_id, name) values (14, 'Insein township');
insert into township (division_id, name) values (14, 'Mingaladon township');
insert into township (division_id, name) values (14, 'Shwepyitha township');
insert into township (division_id, name) values (14, 'Hlegu township');
insert into township (division_id, name) values (14, 'Hmawbi township');
insert into township (division_id, name) values (14, 'Htantabin township');
insert into township (division_id, name) values (14, 'Taikkyi township');
insert into township (division_id, name) values (14, 'Dala township');
insert into township (division_id, name) values (14, 'Seikkyi Kanaungto township');
insert into township (division_id, name) values (14, 'Cocokyun township');
insert into township (division_id, name) values (14, 'Kawhmu township');
insert into township (division_id, name) values (14, 'Kayan township');
insert into township (division_id, name) values (14, 'Kungyangon township');
insert into township (division_id, name) values (14, 'Kyauktan township');
insert into township (division_id, name) values (14, 'Thanlyin township');
insert into township (division_id, name) values (14, 'Thongwa township');
insert into township (division_id, name) values (14, 'Twante township');
insert into township (division_id, name) values (14, 'Tada Subtownship');
insert into township (division_id, name) values (14, 'Ahlon township');
insert into township (division_id, name) values (14, 'Bahan township');
insert into township (division_id, name) values (14, 'Dagon township');
insert into township (division_id, name) values (14, 'Kyauktada township');
insert into township (division_id, name) values (14, 'Kyimyindaing township');
insert into township (division_id, name) values (14, 'Lanmadaw township');
insert into township (division_id, name) values (14, 'Latha township');
insert into township (division_id, name) values (14, 'Pabedan township');
insert into township (division_id, name) values (14, 'Sanchaung township');
insert into township (division_id, name) values (14, 'Seikkan township');
insert into township (division_id, name) values (14, 'Hlaing township');
insert into township (division_id, name) values (14, 'Kamayut township');
insert into township (division_id, name) values (14, 'Mayangon township');

-- Naypyidaw
insert into township (division_id, name) values (15, 'Ottarathiri township');
insert into township (division_id, name) values (15, 'Pobbathiri township');
insert into township (division_id, name) values (15, 'Tatkon township');
insert into township (division_id, name) values (15, 'Zeyarthiri township');
insert into township (division_id, name) values (15, 'Dekkhinathiri township');
insert into township (division_id, name) values (15, 'Lewe township');
insert into township (division_id, name) values (15, 'Pyinmana township');
insert into township (division_id, name) values (15, 'Zabuthiri township');